# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_node.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10model_node.proto\x12\nmodel_node\"H\n\x0e\x46orwardRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x05\x12\x12\n\nbatch_hash\x18\x02 \x01(\t\x12\x10\n\x08is_train\x18\x03 \x01(\x08\"G\n\x0f\x46orwardResponse\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x05\x12\x12\n\nbatch_hash\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\x0c\"Q\n\x0f\x42\x61\x63kwardRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x05\x12\x12\n\nbatch_hash\x18\x02 \x01(\t\x12\x18\n\x10reference_output\x18\x03 \x01(\x0c\"W\n\x10\x42\x61\x63kwardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\x05\x12\x12\n\nbatch_hash\x18\x03 \x01(\t\x12\x0c\n\x04loss\x18\x04 \x01(\x02\"\r\n\x0b\x45xitRequest\"\x1f\n\x0c\x45xitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd7\x01\n\tModelNode\x12\x44\n\x07\x46orward\x12\x1a.model_node.ForwardRequest\x1a\x1b.model_node.ForwardResponse\"\x00\x12G\n\x08\x42\x61\x63kward\x12\x1b.model_node.BackwardRequest\x1a\x1c.model_node.BackwardResponse\"\x00\x12;\n\x04\x45xit\x12\x17.model_node.ExitRequest\x1a\x18.model_node.ExitResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDREQUEST']._serialized_start=32
  _globals['_FORWARDREQUEST']._serialized_end=104
  _globals['_FORWARDRESPONSE']._serialized_start=106
  _globals['_FORWARDRESPONSE']._serialized_end=177
  _globals['_BACKWARDREQUEST']._serialized_start=179
  _globals['_BACKWARDREQUEST']._serialized_end=260
  _globals['_BACKWARDRESPONSE']._serialized_start=262
  _globals['_BACKWARDRESPONSE']._serialized_end=349
  _globals['_EXITREQUEST']._serialized_start=351
  _globals['_EXITREQUEST']._serialized_end=364
  _globals['_EXITRESPONSE']._serialized_start=366
  _globals['_EXITRESPONSE']._serialized_end=397
  _globals['_MODELNODE']._serialized_start=400
  _globals['_MODELNODE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
