syntax = "proto3";

package model_node;

service ModelNode {
  rpc Forward (ForwardRequest) returns (ForwardResponse) {}
  rpc Backward (BackwardRequest) returns (BackwardResponse) {}
  rpc Exit (ExitRequest) returns (ExitResponse) {}
}

message ForwardRequest {
  int32 batch_id = 1;
  string batch_hash = 2;
  bool is_train = 3;
}

message ForwardResponse {
  int32 batch_id = 1;
  string batch_hash = 2;
  bytes output = 3;  // Logits for both reference and training models
}

message BackwardRequest {
  int32 batch_id = 1;
  string batch_hash = 2;
  bytes reference_output = 3;
}

message BackwardResponse {
  bool success = 1;
  int32 batch_id = 2;
  string batch_hash = 3;
  float loss = 4;
}

message ExitRequest {}

message ExitResponse {
  bool success = 1;
}